volumes:
    mongo-data:
        external: true

services:
    fastapi:
        environment:
            DATABASE_URL: mongodb://example_user:secret@mongo
            DB_NAME: mongo
            CORS_HOST: http://localhost:5173
            SIGNING_KEY: f8c7dcb73b3b8dff6b242c870e95f285ff3b3be284f666468d09e9e7cb4d1c36
        build:
            context: api
            dockerfile: Dockerfile.dev
        ports:
            - 8000:8000
        user: "1000:1000" # on macOS and Linux, replace this with your real user id and group id
        volumes:
            - ./api:/app

    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        user: "1000:1000" # on macOS and Linux, replace this with your real user id and group id
        volumes:
            - ./ghi:/app
        environment:
            VITE_API_HOST: http://localhost:8000
            VITE_NODE_ENV: development
            VITE_HOST_OS: ${OS}
            VITE_EXERCISE_DB_KEY: key
        ports:
            - "5173:5173"

    mongo:
        image: mongo:5
        volumes:
            - mongo-data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: example_user
            MONGO_INITDB_ROOT_PASSWORD: secret

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: example_user
            ME_CONFIG_MONGODB_ADMINPASSWORD: secret
            ME_CONFIG_MONGODB_URL: mongodb://example_user:secret@mongo:27017/
